button added
Spyware007/Animating-Buttons pull request #1495
Opened 2023-06-22 07:51 UTC by karthiknadar1204

## Fixes Issue

Closes #1230 

## Changes proposed

## Screenshots

## Checklist
Please refer pr #1448 for the proposed changes

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

## Note to reviewers

2023-06-22 13:00 UTC, adity2911 commented
Resolve conflicts ASAP and tag me

2023-06-22 14:24 UTC, karthiknadar1204 commented
Honestly someone named lakhan ya something seems to be adding someting again and again, this was te second time I had to resolve the conflict manually

2023-06-22 17:15 UTC, Souravvmishra requested changes
You forget to remove extra = from line number 865 in data.js

2023-06-22 17:31 UTC, karthiknadar1204 commented
@Souravvmishra Please check now

2023-06-22 17:34 UTC, karthiknadar1204 commented
<img width="1792" alt="Screenshot 2023-06-22 at 11 03 31 PM" src="https://github.com/Spyware007/Animating-Buttons/assets/95973644/8127941a-2bcd-44c6-a08f-d33353f39396">

Please see this snap @Souravvmishra , I can't find any = in data.js line 865

2023-06-22 17:59 UTC, karthiknadar1204 commented
Good to go ?
@Souravvmishra

2023-06-23 04:33 UTC, adity2911 requested changes

2023-06-23 04:33 UTC, adity2911 commented on src/Data.js
make sure that you only add significant data files in data.js

2023-06-23 06:53 UTC, karthiknadar1204 commented
in data.js , i only added my github username

2023-06-23 06:58 UTC, adity2911 commented
I can see around 20 lines added to the file data.js. Look into it at the files changed tab.

2023-06-23 07:16 UTC, karthiknadar1204 commented
not added by me @adity2911 ,other pr's are getting merged so branch conflicts,I'll clear the present conflict,then you check again

2023-06-23 07:27 UTC, merged